#!/usr/bin/env python3.11
"""
build-index-json.py — views over the citation ledger (M4-RUNBOOK step 4).

    index/citations.tsv ──► site/src/data/scripture/<book>.json
                       └──► site/src/data/scripture/index.json   (the book list)

It computes NOTHING about citations. Every judgement about what a citation is, where it
points, and whether the two layers disagree was made by `build-citations.py` and frozen
in the ledger. This file only regroups and renders. (M4-RUNBOOK §5.)

★ The one decision that shapes everything here, and the one that differs from
Bonaventure's equivalent:

    A LOCUS IS A CITATION, NOT A RECORD.

Milton cites in Latin and Sumner cites in English, and where their numbering diverges
they print DIFFERENT DIGITS FOR THE SAME VERSE — 299 times across 21 chunks, most of it
in the Psalms, the most-cited book in the treatise (M4-RUNBOOK §6b). Grouping by the
printed target would scatter one act of citation into two unrelated entries four verses
apart. So loci are grouped by `divergence_id` where the ledger paired the two layers,
and filed under `witness_target` — the verse both layers are pointing at — while going
on to SHOW both printed forms. Displaying the disagreement is the point of the edition;
the index must not resolve it away, and must not be scrambled by it either.

Usage:
    python3.11 tools/build-index-json.py
"""

from __future__ import annotations

import collections
import csv
import io
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LEDGER = os.path.join(ROOT, "index", "citations.tsv")
BOOKS_JSON = os.path.join(ROOT, "tools", "scripture-books.json")
CONTENT = os.path.join(ROOT, "site", "src", "data", "content.json")
OUT_DIR = os.path.join(ROOT, "site", "src", "data", "scripture")

SNIPPET_CHARS = 190
ABOUT = ("Generated by tools/build-index-json.py from index/citations.tsv. "
         "Do not hand-edit; regenerate. Citations are shown AS PRINTED in each layer "
         "(CONVENTIONS §3); where the layers disagree the entry is filed under the "
         "verse both are pointing at.")


def slug(key):
    return re.sub(r"[^a-z0-9]", "", key.lower())


def para_anchor(chunk_id, layer, para):
    """Deep link to one paragraph of one layer.

    ⚠ Must match `anchorId` in site/src/app/browse/[book]/[chapter]/text-reader.tsx —
    change the two together. Scoped by CHUNK because a chapter transcribed in parts
    restarts its {¶N} numbering at 1 in every part (CONVENTIONS §8d).
    """
    n = re.sub(r"[^0-9]+", "-", para.strip("{}¶")).strip("-")
    return f"{chunk_id}-{layer}-p{n}"


def parse_target(t):
    """`Eccl 4:5,6` / `Rev 1` / `Rom 13:1 &c.` -> (book, chapter, first verse or None)."""
    m = re.match(r"^(\S+)\s+(\d+)(?::([\d,]+))?", t or "")
    if not m:
        return None
    verses = m.group(3)
    first = int(verses.split(",")[0]) if verses else None
    return m.group(1), int(m.group(2)), first


def chapter_routes():
    """chunk id -> the URL and headings of the page that actually serves it.

    Built from content.json, the site's own view of the corpus, so a URL built here is
    one the site really serves. ⚠ Several chunks share a chapter page (§8d).
    """
    with io.open(CONTENT, encoding="utf-8") as fh:
        chunks = json.load(fh)
    out = {}
    for c in chunks:
        titles = c.get("titles") or {}
        out[c["id"]] = {
            "url": f"/browse/{c['book']}/{c['chapter']}",
            "book": c["book"],
            "chapter": c["chapter"],
            "title": titles.get("la") or next(iter(titles.values()), c["id"]),
            "titleEn": titles.get("en-sumner", ""),
        }
    return out


def snippets_for(rows):
    """Slice context around each citation, out of the chunk file it came from.

    Rebuilt from the chunks rather than stored in the ledger, so the two cannot drift.
    """
    want = collections.defaultdict(set)
    for r in rows:
        want[r["chunk_id"]].add(r["layer"])

    bodies = {}
    for cid in want:
        path = os.path.join(ROOT, "chunks", cid + ".md")
        if not os.path.exists(path):
            continue
        raw = io.open(path, encoding="utf-8").read().split("\n## Notes")[0]
        for part in raw.split("\n## ")[1:]:
            head, _, text = part.partition("\n")
            bodies[(cid, head.strip())] = text

    out = {}
    for r in rows:
        text = bodies.get((r["chunk_id"], r["layer"]), "")
        raw = r["raw_text"]
        i = text.find(raw[:38]) if raw else -1
        lo = max(0, i - SNIPPET_CHARS // 3) if i >= 0 else 0
        frag = re.sub(r"\s+", " ", text[lo:lo + SNIPPET_CHARS]).strip()
        frag = re.sub(r"\[\^[^\]]+\]|<!--.*?-->|\{¶[^}]*\}", "", frag)
        frag = re.sub(r"\s+", " ", frag.replace("*", "")).strip()
        out[r["id"]] = ("…" if lo else "") + frag + "…"
    return out


def main():
    with io.open(LEDGER, encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh, delimiter="\t"))
    for i, r in enumerate(rows):
        r["id"] = f"{r['chunk_id']}:{r['layer']}:{r['para']}:{r['seq']}"
        r["_i"] = i

    meta = {b["key"]: b for b in json.load(io.open(BOOKS_JSON, encoding="utf-8"))["books"]}
    routes = chapter_routes()
    snips = snippets_for(rows)

    # ── group records into loci ────────────────────────────────────────────────
    # A divergence_id means the ledger already paired two records as one citation seen
    # twice. Everything else stands alone.
    # ⚠ Only a `plausible` pair is merged. align() pairs by position inside a paragraph,
    # and one insertion can slide everything after it — La `Psal. xxv. 22.` got paired
    # with En `iii. 8.`, which are simply different verses. Merging that would file
    # Milton's Ps 25:22 under Ps 3:8: not a divergence to display but a false statement
    # about where he cites. The parser marks such pairs `suspect`; they stay two loci and
    # are listed in the QA report for a reader.
    by_div = collections.defaultdict(list)
    loci = []
    for r in rows:
        if r["divergence_id"] and r["pair_confidence"] == "plausible":
            by_div[r["divergence_id"]].append(r)
        else:
            loci.append([r])
    loci.extend(by_div.values())

    grouped = collections.defaultdict(lambda: collections.defaultdict(list))
    skipped = collections.Counter()
    for group in loci:
        group.sort(key=lambda r: r["_i"])
        head = group[0]
        tgt = parse_target(head["witness_target"] or head["target"])
        if not tgt:
            skipped["unparseable target"] += 1
            continue
        book, chap, verse = tgt
        route = routes.get(head["chunk_id"])
        if not route:
            skipped["chunk not on the site"] += 1
            continue
        witnesses = [{
            "layer": r["layer"],
            "raw": r["raw_text"],
            "printed": r["target"],
            "anchor": para_anchor(r["chunk_id"], r["layer"], r["para"]),
            "para": r["para"],
            "snippet": snips.get(r["id"], ""),
        } for r in group]
        grouped[book][chap].append({
            "chunk": head["chunk_id"],
            "url": route["url"],
            "bookNum": route["book"],
            "chapterNum": route["chapter"],
            "title": route["title"],
            "titleEn": route["titleEn"],
            "verse": verse,
            "witness": head["witness_target"] or head["target"],
            # True when the two layers print DIFFERENT numbers for this same verse —
            # the thing this edition exists to show. Drives the display.
            "diverges": len({w["printed"] for w in witnesses}) > 1,
            "resolution": head["resolution"],
            "witnesses": witnesses,
        })

    # ── emit ───────────────────────────────────────────────────────────────────
    os.makedirs(OUT_DIR, exist_ok=True)
    for stale in os.listdir(OUT_DIR):
        if stale.endswith(".json"):
            os.remove(os.path.join(OUT_DIR, stale))

    listing, total, diverging = [], 0, 0
    for key, chapters in grouped.items():
        b = meta.get(key)
        if not b:
            skipped["book not in scripture-books.json"] += 1
            continue
        chapter_list = [{
            "chapter": n,
            "loci": sorted(chapters[n], key=lambda l: (l["verse"] or 0, l["chunk"])),
        } for n in sorted(chapters)]
        count = sum(len(c["loci"]) for c in chapter_list)
        divs = sum(1 for c in chapter_list for l in c["loci"] if l["diverges"])
        total += count
        diverging += divs
        doc = {
            "_about": ABOUT,
            "key": key, "slug": slug(key),
            "nameEn": b["nameEn"], "nameLa": b["nameLa"],
            "order": b["order"], "testament": b.get("testament", ""),
            "count": count, "diverging": divs,
            "chapters": chapter_list,
        }
        with io.open(os.path.join(OUT_DIR, slug(key) + ".json"), "w", encoding="utf-8") as fh:
            json.dump(doc, fh, ensure_ascii=False, indent=1)
        listing.append({k: doc[k] for k in
                        ("key", "slug", "nameEn", "nameLa", "order", "testament",
                         "count", "diverging")})

    listing.sort(key=lambda b: (b["order"], b["key"]))
    with io.open(os.path.join(OUT_DIR, "index.json"), "w", encoding="utf-8") as fh:
        json.dump({"_about": ABOUT, "books": listing,
                   "total": total, "diverging": diverging}, fh,
                  ensure_ascii=False, indent=1)

    print(f"{total} loci · {len(listing)} books · {diverging} showing a layer divergence")
    for reason, n in skipped.items():
        print(f"  skipped {n}: {reason}")


if __name__ == "__main__":
    main()
